# Generated by Django 2.1.15 on 2020-06-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='bot',
        ),
        migrations.RemoveField(
            model_name='history',
            name='url',
        ),
    ]
